services:
  whisper_ros_cudnn:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: whisper_ros_cudnn
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - ..:/catkin_ws/src/whisper_ros
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - $HOME/vscode-server:$HOME/.vscode-server
      - /dev/snd:/dev/snd
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    environment:
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      #- ROS_MASTER_URI=http://10.0.0.143:11311
      #- ROS_IP=10.0.0.238
    devices:
      - "/dev/snd"
    cap_add:
      - SYS_RAWIO
    security_opt:
      - seccomp:unconfined
    privileged: true
    stdin_open: true
    tty: true
